/** Generated household appliance/furniture set used by the real item catalog. */
export interface FeaturedHouseholdItem {
  id: string;
  name: string;
  cat: "가전" | "가구";
  sub: string;
  vol: number;
  icon: string;
}

export const FEATURED_HOUSEHOLD_100: FeaturedHouseholdItem[] = [
  { id: "four-door-refrigerator-01", name: "4도어냉장고", cat: "가전", sub: "대형가전", vol: 1, icon: "/assets/items-3d/household-100/four-door-refrigerator-01.webp" },
  { id: "kimchi-standing-refrigerator-01", name: "스탠드김치냉장고", cat: "가전", sub: "대형가전", vol: 0.7, icon: "/assets/items-3d/household-100/kimchi-standing-refrigerator-01.webp" },
  { id: "kimchi-chest-refrigerator-01", name: "뚜껑형김치냉장고", cat: "가전", sub: "대형가전", vol: 0.6, icon: "/assets/items-3d/household-100/kimchi-chest-refrigerator-01.webp" },
  { id: "water-purifier-refrigerator-01", name: "정수기냉장고", cat: "가전", sub: "대형가전", vol: 0.8, icon: "/assets/items-3d/household-100/water-purifier-refrigerator-01.webp" },
  { id: "top-load-washer-01", name: "통돌이세탁기", cat: "가전", sub: "대형가전", vol: 0.6, icon: "/assets/items-3d/household-100/top-load-washer-01.webp" },
  { id: "dryer-tower-01", name: "의류건조기타워", cat: "가전", sub: "대형가전", vol: 0.9, icon: "/assets/items-3d/household-100/dryer-tower-01.webp" },
  { id: "clothing-care-machine-01", name: "의류관리기", cat: "가전", sub: "대형가전", vol: 0.5, icon: "/assets/items-3d/household-100/clothing-care-machine-01.webp" },
  { id: "builtin-dishwasher-01", name: "빌트인식기세척기", cat: "가전", sub: "대형가전", vol: 0.4, icon: "/assets/items-3d/household-100/builtin-dishwasher-01.webp" },
  { id: "electric-oven-01", name: "전기오븐", cat: "가전", sub: "대형가전", vol: 0.2, icon: "/assets/items-3d/household-100/electric-oven-01.webp" },
  { id: "gas-oven-range-01", name: "가스오븐레인지", cat: "가전", sub: "대형가전", vol: 0.5, icon: "/assets/items-3d/household-100/gas-oven-range-01.webp" },
  { id: "light-wave-oven-01", name: "광파오븐", cat: "가전", sub: "대형가전", vol: 0.1, icon: "/assets/items-3d/household-100/light-wave-oven-01.webp" },
  { id: "bodyfriend-massage-chair-01", name: "바디프렌드안마의자", cat: "가전", sub: "대형가전", vol: 0.9, icon: "/assets/items-3d/household-100/bodyfriend-massage-chair-01.webp" },
  { id: "ceragem-massager-01", name: "세라젬마사지기", cat: "가전", sub: "대형가전", vol: 0.7, icon: "/assets/items-3d/household-100/ceragem-massager-01.webp" },
  { id: "motion-bed-01", name: "모션베드", cat: "가전", sub: "대형가전", vol: 1, icon: "/assets/items-3d/household-100/motion-bed-01.webp" },
  { id: "electric-adjustable-bed-01", name: "전동침대", cat: "가전", sub: "대형가전", vol: 1, icon: "/assets/items-3d/household-100/electric-adjustable-bed-01.webp" },
  { id: "large-tv-stand-01", name: "대형TV스탠드", cat: "가전", sub: "대형가전", vol: 0.3, icon: "/assets/items-3d/household-100/large-tv-stand-01.webp" },
  { id: "large-wall-air-conditioner-01", name: "벽걸이대형에어컨", cat: "가전", sub: "대형가전", vol: 0.3, icon: "/assets/items-3d/household-100/large-wall-air-conditioner-01.webp" },
  { id: "system-air-conditioner-01", name: "시스템에어컨", cat: "가전", sub: "대형가전", vol: 0.3, icon: "/assets/items-3d/household-100/system-air-conditioner-01.webp" },
  { id: "hot-water-mat-boiler-01", name: "온수매트보일러", cat: "가전", sub: "대형가전", vol: 0.05, icon: "/assets/items-3d/household-100/hot-water-mat-boiler-01.webp" },
  { id: "large-air-purifier-01", name: "대형공기청정기", cat: "가전", sub: "대형가전", vol: 0.2, icon: "/assets/items-3d/household-100/large-air-purifier-01.webp" },
  { id: "ice-maker-01", name: "가정용제빙기", cat: "가전", sub: "대형가전", vol: 0.1, icon: "/assets/items-3d/household-100/ice-maker-01.webp" },
  { id: "large-kimchi-refrigerator-01", name: "대형김치냉장고", cat: "가전", sub: "대형가전", vol: 0.8, icon: "/assets/items-3d/household-100/large-kimchi-refrigerator-01.webp" },
  { id: "builtin-refrigerator-01", name: "빌트인냉장고", cat: "가전", sub: "대형가전", vol: 0.9, icon: "/assets/items-3d/household-100/builtin-refrigerator-01.webp" },
  { id: "washer-dryer-combo-01", name: "세탁건조겸용기", cat: "가전", sub: "대형가전", vol: 0.7, icon: "/assets/items-3d/household-100/washer-dryer-combo-01.webp" },
  { id: "large-water-purifier-01", name: "대형정수기", cat: "가전", sub: "대형가전", vol: 0.2, icon: "/assets/items-3d/household-100/large-water-purifier-01.webp" },
  { id: "water-softener-01", name: "연수기", cat: "가전", sub: "대형가전", vol: 0.15, icon: "/assets/items-3d/household-100/water-softener-01.webp" },
  { id: "tv-75-inch-01", name: "대형TV75인치", cat: "가전", sub: "대형가전", vol: 0.2, icon: "/assets/items-3d/household-100/tv-75-inch-01.webp" },
  { id: "tv-85-inch-01", name: "대형TV85인치", cat: "가전", sub: "대형가전", vol: 0.25, icon: "/assets/items-3d/household-100/tv-85-inch-01.webp" },
  { id: "fireplace-heater-01", name: "벽난로히터", cat: "가전", sub: "대형가전", vol: 0.3, icon: "/assets/items-3d/household-100/fireplace-heater-01.webp" },
  { id: "four-door-kimchi-refrigerator-01", name: "김치냉장고4도어", cat: "가전", sub: "대형가전", vol: 0.8, icon: "/assets/items-3d/household-100/four-door-kimchi-refrigerator-01.webp" },
  { id: "hot-cold-water-purifier-01", name: "냉온정수기", cat: "가전", sub: "대형가전", vol: 0.2, icon: "/assets/items-3d/household-100/hot-cold-water-purifier-01.webp" },
  { id: "home-massage-bed-01", name: "가정용안마베드", cat: "가전", sub: "대형가전", vol: 0.9, icon: "/assets/items-3d/household-100/home-massage-bed-01.webp" },
  { id: "kimchi-stand-refrigerator-01", name: "김치스텐드냉장고", cat: "가전", sub: "대형가전", vol: 0.7, icon: "/assets/items-3d/household-100/kimchi-stand-refrigerator-01.webp" },
  { id: "ceragem-01", name: "세라잼", cat: "가전", sub: "대형가전", vol: 0.7, icon: "/assets/items-3d/household-100/ceragem-01.webp" },
  { id: "sofa-01", name: "소파", cat: "가구", sub: "거실가구", vol: 0.6, icon: "/assets/items-3d/household-100/sofa-01.webp" },
  { id: "two-seat-sofa-01", name: "2인소파", cat: "가구", sub: "거실가구", vol: 0.7, icon: "/assets/items-3d/household-100/two-seat-sofa-01.webp" },
  { id: "three-seat-sofa-01", name: "3인소파", cat: "가구", sub: "거실가구", vol: 0.9, icon: "/assets/items-3d/household-100/three-seat-sofa-01.webp" },
  { id: "four-seat-sofa-01", name: "4인소파", cat: "가구", sub: "거실가구", vol: 1.1, icon: "/assets/items-3d/household-100/four-seat-sofa-01.webp" },
  { id: "armchair-01", name: "1인안락의자", cat: "가구", sub: "거실가구", vol: 0.4, icon: "/assets/items-3d/household-100/armchair-01.webp" },
  { id: "stool-01", name: "스툴", cat: "가구", sub: "거실가구", vol: 0.1, icon: "/assets/items-3d/household-100/stool-01.webp" },
  { id: "living-room-table-01", name: "거실테이블", cat: "가구", sub: "거실가구", vol: 0.3, icon: "/assets/items-3d/household-100/living-room-table-01.webp" },
  { id: "sofa-side-table-01", name: "소파테이블", cat: "가구", sub: "거실가구", vol: 0.15, icon: "/assets/items-3d/household-100/sofa-side-table-01.webp" },
  { id: "console-table-01", name: "콘솔테이블", cat: "가구", sub: "거실가구", vol: 0.2, icon: "/assets/items-3d/household-100/console-table-01.webp" },
  { id: "tv-stand-01", name: "TV장", cat: "가구", sub: "거실가구", vol: 0.4, icon: "/assets/items-3d/household-100/tv-stand-01.webp" },
  { id: "living-room-cabinet-01", name: "거실장", cat: "가구", sub: "거실가구", vol: 0.5, icon: "/assets/items-3d/household-100/living-room-cabinet-01.webp" },
  { id: "display-cabinet-01", name: "장식장", cat: "가구", sub: "거실가구", vol: 0.5, icon: "/assets/items-3d/household-100/display-cabinet-01.webp" },
  { id: "showcase-cabinet-01", name: "진열장", cat: "가구", sub: "거실가구", vol: 0.5, icon: "/assets/items-3d/household-100/showcase-cabinet-01.webp" },
  { id: "art-wall-cabinet-01", name: "아트월수납장", cat: "가구", sub: "거실가구", vol: 0.5, icon: "/assets/items-3d/household-100/art-wall-cabinet-01.webp" },
  { id: "living-room-shelf-01", name: "거실선반", cat: "가구", sub: "거실가구", vol: 0.2, icon: "/assets/items-3d/household-100/living-room-shelf-01.webp" },
  { id: "audio-cabinet-01", name: "오디오장", cat: "가구", sub: "거실가구", vol: 0.3, icon: "/assets/items-3d/household-100/audio-cabinet-01.webp" },
  { id: "bean-bag-01", name: "빈백", cat: "가구", sub: "거실가구", vol: 0.3, icon: "/assets/items-3d/household-100/bean-bag-01.webp" },
  { id: "carpet-01", name: "카펫", cat: "가구", sub: "거실가구", vol: 0.2, icon: "/assets/items-3d/household-100/carpet-01.webp" },
  { id: "rug-01", name: "러그", cat: "가구", sub: "거실가구", vol: 0.1, icon: "/assets/items-3d/household-100/rug-01.webp" },
  { id: "living-massage-chair-01", name: "안마의자거실", cat: "가구", sub: "거실가구", vol: 0.8, icon: "/assets/items-3d/household-100/living-massage-chair-01.webp" },
  { id: "rocking-chair-01", name: "흔들의자", cat: "가구", sub: "거실가구", vol: 0.4, icon: "/assets/items-3d/household-100/rocking-chair-01.webp" },
  { id: "single-recliner-01", name: "1인용리클라이너", cat: "가구", sub: "거실가구", vol: 0.6, icon: "/assets/items-3d/household-100/single-recliner-01.webp" },
  { id: "living-bench-01", name: "거실벤치", cat: "가구", sub: "거실가구", vol: 0.3, icon: "/assets/items-3d/household-100/living-bench-01.webp" },
  { id: "magazine-rack-01", name: "신문꽂이", cat: "가구", sub: "거실가구", vol: 0.05, icon: "/assets/items-3d/household-100/magazine-rack-01.webp" },
  { id: "plant-stand-01", name: "화분받침대", cat: "가구", sub: "거실가구", vol: 0.05, icon: "/assets/items-3d/household-100/plant-stand-01.webp" },
  { id: "storage-bench-01", name: "거실수납벤치", cat: "가구", sub: "거실가구", vol: 0.3, icon: "/assets/items-3d/household-100/storage-bench-01.webp" },
  { id: "bed-01", name: "침대", cat: "가구", sub: "침실가구", vol: 0.9, icon: "/assets/items-3d/household-100/bed-01.webp" },
  { id: "single-bed-01", name: "싱글침대", cat: "가구", sub: "침실가구", vol: 0.7, icon: "/assets/items-3d/household-100/single-bed-01.webp" },
  { id: "super-single-bed-01", name: "슈퍼싱글침대", cat: "가구", sub: "침실가구", vol: 0.8, icon: "/assets/items-3d/household-100/super-single-bed-01.webp" },
  { id: "double-bed-01", name: "더블침대", cat: "가구", sub: "침실가구", vol: 1, icon: "/assets/items-3d/household-100/double-bed-01.webp" },
  { id: "queen-bed-01", name: "퀸침대", cat: "가구", sub: "침실가구", vol: 1.1, icon: "/assets/items-3d/household-100/queen-bed-01.webp" },
  { id: "king-bed-01", name: "킹침대", cat: "가구", sub: "침실가구", vol: 1.3, icon: "/assets/items-3d/household-100/king-bed-01.webp" },
  { id: "mattress-topper-01", name: "토퍼", cat: "가구", sub: "침실가구", vol: 0.15, icon: "/assets/items-3d/household-100/mattress-topper-01.webp" },
  { id: "bed-frame-01", name: "침대프레임", cat: "가구", sub: "침실가구", vol: 0.6, icon: "/assets/items-3d/household-100/bed-frame-01.webp" },
  { id: "headboard-01", name: "헤드보드", cat: "가구", sub: "침실가구", vol: 0.2, icon: "/assets/items-3d/household-100/headboard-01.webp" },
  { id: "family-bed-01", name: "패밀리침대", cat: "가구", sub: "침실가구", vol: 1.5, icon: "/assets/items-3d/household-100/family-bed-01.webp" },
  { id: "floor-bed-platform-01", name: "평상", cat: "가구", sub: "침실가구", vol: 0.8, icon: "/assets/items-3d/household-100/floor-bed-platform-01.webp" },
  { id: "stone-bed-01", name: "돌침대", cat: "가구", sub: "침실가구", vol: 1.4, icon: "/assets/items-3d/household-100/stone-bed-01.webp" },
  { id: "clay-bed-01", name: "흙침대", cat: "가구", sub: "침실가구", vol: 1.4, icon: "/assets/items-3d/household-100/clay-bed-01.webp" },
  { id: "dressroom-shelf-01", name: "드레스룸선반", cat: "가구", sub: "침실가구", vol: 0.4, icon: "/assets/items-3d/household-100/dressroom-shelf-01.webp" },
  { id: "vanity-chair-01", name: "화장대의자", cat: "가구", sub: "침실가구", vol: 0.1, icon: "/assets/items-3d/household-100/vanity-chair-01.webp" },
  { id: "three-drawer-chest-01", name: "3단서랍장", cat: "가구", sub: "침실가구", vol: 0.4, icon: "/assets/items-3d/household-100/three-drawer-chest-01.webp" },
  { id: "five-drawer-chest-01", name: "5단서랍장", cat: "가구", sub: "침실가구", vol: 0.6, icon: "/assets/items-3d/household-100/five-drawer-chest-01.webp" },
  { id: "bedside-table-01", name: "침실협탁2", cat: "가구", sub: "침실가구", vol: 0.1, icon: "/assets/items-3d/household-100/bedside-table-01.webp" },
  { id: "bedding-cabinet-01", name: "이불장", cat: "가구", sub: "침실가구", vol: 0.7, icon: "/assets/items-3d/household-100/bedding-cabinet-01.webp" },
  { id: "vanity-mirror-stand-01", name: "경대", cat: "가구", sub: "침실가구", vol: 0.3, icon: "/assets/items-3d/household-100/vanity-mirror-stand-01.webp" },
  { id: "dining-table-01", name: "식탁", cat: "가구", sub: "주방가구", vol: 0.5, icon: "/assets/items-3d/household-100/dining-table-01.webp" },
  { id: "two-seat-dining-table-01", name: "2인식탁", cat: "가구", sub: "주방가구", vol: 0.4, icon: "/assets/items-3d/household-100/two-seat-dining-table-01.webp" },
  { id: "four-seat-dining-table-01", name: "4인식탁", cat: "가구", sub: "주방가구", vol: 0.6, icon: "/assets/items-3d/household-100/four-seat-dining-table-01.webp" },
  { id: "six-seat-dining-table-01", name: "6인식탁", cat: "가구", sub: "주방가구", vol: 0.9, icon: "/assets/items-3d/household-100/six-seat-dining-table-01.webp" },
  { id: "dining-chair-01", name: "식탁의자", cat: "가구", sub: "주방가구", vol: 0.1, icon: "/assets/items-3d/household-100/dining-chair-01.webp" },
  { id: "dining-bench-01", name: "벤치의자", cat: "가구", sub: "주방가구", vol: 0.2, icon: "/assets/items-3d/household-100/dining-bench-01.webp" },
  { id: "home-bar-table-01", name: "홈바테이블", cat: "가구", sub: "주방가구", vol: 0.4, icon: "/assets/items-3d/household-100/home-bar-table-01.webp" },
  { id: "bar-stool-01", name: "바스툴", cat: "가구", sub: "주방가구", vol: 0.1, icon: "/assets/items-3d/household-100/bar-stool-01.webp" },
  { id: "cupboard-01", name: "찬장", cat: "가구", sub: "주방가구", vol: 0.6, icon: "/assets/items-3d/household-100/cupboard-01.webp" },
  { id: "range-stand-01", name: "레인지대", cat: "가구", sub: "주방가구", vol: 0.3, icon: "/assets/items-3d/household-100/range-stand-01.webp" },
  { id: "microwave-shelf-01", name: "전자레인지선반", cat: "가구", sub: "주방가구", vol: 0.2, icon: "/assets/items-3d/household-100/microwave-shelf-01.webp" },
  { id: "fridge-base-stand-01", name: "김치냉장고받침", cat: "가구", sub: "주방가구", vol: 0.1, icon: "/assets/items-3d/household-100/fridge-base-stand-01.webp" },
  { id: "island-storage-01", name: "주방아일랜드수납", cat: "가구", sub: "주방가구", vol: 0.5, icon: "/assets/items-3d/household-100/island-storage-01.webp" },
  { id: "dish-rack-shelf-01", name: "식기정리선반", cat: "가구", sub: "주방가구", vol: 0.2, icon: "/assets/items-3d/household-100/dish-rack-shelf-01.webp" },
  { id: "kitchen-slim-cabinet-01", name: "주방틈새장", cat: "가구", sub: "주방가구", vol: 0.2, icon: "/assets/items-3d/household-100/kitchen-slim-cabinet-01.webp" },
  { id: "rice-storage-cabinet-01", name: "쌀통수납장", cat: "가구", sub: "주방가구", vol: 0.2, icon: "/assets/items-3d/household-100/rice-storage-cabinet-01.webp" },
  { id: "kitchen-storage-bench-01", name: "주방벤치수납", cat: "가구", sub: "주방가구", vol: 0.3, icon: "/assets/items-3d/household-100/kitchen-storage-bench-01.webp" },
  { id: "wine-rack-01", name: "와인랙", cat: "가구", sub: "주방가구", vol: 0.15, icon: "/assets/items-3d/household-100/wine-rack-01.webp" },
  { id: "kitchen-utility-shelf-01", name: "다용도주방선반", cat: "가구", sub: "주방가구", vol: 0.2, icon: "/assets/items-3d/household-100/kitchen-utility-shelf-01.webp" },
  { id: "kitchen-trolley-01", name: "주방트롤리", cat: "가구", sub: "주방가구", vol: 0.2, icon: "/assets/items-3d/household-100/kitchen-trolley-01.webp" },
];
