// 짐픽 품목 마스터 생성기 (20개 카테고리 전체).
// 큐레이션한 {한글, 영문슬러그, [수량], [부피m³]} → 데이터 TS + 프롬프트 CSV + 검증 리포트.
// 중복(한글명/파일명)·파일명 규칙(소문자+하이픈)·카테고리별 개수를 코드가 보장.
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

const REPO = "/home/user/jimpick-ai-move-wiz";
const CATS = {
  "대형가전":{folder:"appliances-large",vol:0.6,emoji:"🧊"},
  "주방가전":{folder:"kitchen-appliance",vol:0.08,emoji:"🍳"},
  "생활가전":{folder:"living-appliance",vol:0.15,emoji:"🔌"},
  "계절가전":{folder:"season-appliance",vol:0.25,emoji:"❄️"},
  "영상·음향기기":{folder:"av",vol:0.12,emoji:"📺"},
  "컴퓨터·사무기기":{folder:"computer-office",vol:0.1,emoji:"🖥️"},
  "거실가구":{folder:"living-furniture",vol:0.5,emoji:"🛋️"},
  "침실가구":{folder:"bedroom-furniture",vol:0.7,emoji:"🛏️"},
  "주방가구":{folder:"kitchen-furniture",vol:0.4,emoji:"🍽️"},
  "아동가구":{folder:"kids-furniture",vol:0.3,emoji:"🧸"},
  "사무가구":{folder:"office-furniture",vol:0.4,emoji:"🪑"},
  "수납가구":{folder:"storage-furniture",vol:0.4,emoji:"🗄️"},
  "욕실용품":{folder:"bath",vol:0.05,emoji:"🛁"},
  "주방용품":{folder:"kitchenware",vol:0.03,emoji:"🥣"},
  "생활용품":{folder:"household",vol:0.05,emoji:"🧺"},
  "청소용품":{folder:"cleaning",vol:0.05,emoji:"🧹"},
  "운동·레저용품":{folder:"sports",vol:0.2,emoji:"🏋️"},
  "캠핑용품":{folder:"camping",vol:0.15,emoji:"⛺"},
  "반려동물용품":{folder:"pet",vol:0.1,emoji:"🐾"},
  "기타 이삿짐 및 폐기물":{folder:"etc-waste",vol:0.2,emoji:"📦"},
};

const DATA = {
  "대형가전":[["냉장고","refrigerator",1,0.9],["양문형냉장고","side-by-side-refrigerator",1,1.0],["4도어냉장고","four-door-refrigerator",1,1.0],["김치냉장고","kimchi-refrigerator",1,0.7],["스탠드김치냉장고","kimchi-standing-refrigerator",1,0.7],["뚜껑형김치냉장고","kimchi-chest-refrigerator",1,0.6],["미니냉장고","mini-refrigerator",1,0.2],["정수기냉장고","water-purifier-refrigerator",1,0.8],["냉동고","freezer",1,0.5],["와인셀러","wine-cellar",1,0.4],["세탁기","washing-machine",1,0.6],["통돌이세탁기","top-load-washer",1,0.6],["드럼세탁기","drum-washing-machine",1,0.6],["건조기","clothes-dryer",1,0.6],["워시타워","wash-tower",1,0.9],["의류건조기타워","dryer-tower",1,0.9],["스타일러","clothes-styler",1,0.5],["의류관리기","clothing-care-machine",1,0.5],["식기세척기","dishwasher",1,0.4],["빌트인식기세척기","builtin-dishwasher",1,0.4],["전기오븐","electric-oven",1,0.2],["가스오븐레인지","gas-oven-range",1,0.5],["광파오븐","light-wave-oven",1,0.1],["안마의자","massage-chair",1,0.8],["바디프렌드안마의자","bodyfriend-massage-chair",1,0.9],["세라젬마사지기","ceragem-massager",1,0.7],["모션베드","motion-bed",1,1.0],["전동침대","electric-adjustable-bed",1,1.0],["대형TV스탠드","large-tv-stand",1,0.3],["벽걸이대형에어컨","large-wall-air-conditioner",1,0.3],["스탠드에어컨","stand-air-conditioner",1,0.4],["시스템에어컨","system-air-conditioner",1,0.3],["온수매트보일러","hot-water-mat-boiler",1,0.05],["대형공기청정기","large-air-purifier",1,0.2],["가정용제빙기","ice-maker",1,0.1],["업소용냉장고","commercial-refrigerator",1,1.1],["업소용냉동고","commercial-freezer",1,1.1],["쇼케이스냉장고","showcase-refrigerator",1,0.9],["대형김치냉장고","large-kimchi-refrigerator",1,0.8],["빌트인냉장고","builtin-refrigerator",1,0.9],["세탁건조겸용기","washer-dryer-combo",1,0.7],["대형정수기","large-water-purifier",1,0.2],["연수기","water-softener",1,0.15],["대형TV75인치","tv-75-inch",1,0.2],["대형TV85인치","tv-85-inch",1,0.25],["벽난로히터","fireplace-heater",1,0.3],["김치냉장고4도어","four-door-kimchi-refrigerator",1,0.8],["냉온정수기","hot-cold-water-purifier",1,0.2],["가정용안마베드","home-massage-bed",1,0.9]],
  "주방가전":[["전자레인지","microwave-oven",1],["에어프라이어","air-fryer",1],["토스터","toaster",1],["전기밥솥","rice-cooker",1],["압력밥솥","pressure-rice-cooker",1],["인덕션","induction-cooktop",1],["하이라이트","highlight-cooktop",1],["가스레인지","gas-stove",1],["휴대용가스버너","portable-gas-burner",1],["커피머신","coffee-machine",1],["캡슐커피머신","capsule-coffee-machine",1],["전기포트","electric-kettle",1],["믹서기","blender",1],["핸드블렌더","hand-blender",1],["원액기","slow-juicer",1],["착즙기","juicer",1],["전기그릴","electric-grill",1],["샌드위치메이커","sandwich-maker",1],["와플메이커","waffle-maker",1],["전기냄비","electric-pot",1],["전기프라이팬","electric-frying-pan",1],["멀티쿠커","multi-cooker",1],["에어프라이어오븐","air-fryer-oven",1],["가정용제면기","noodle-maker",1],["반죽기","stand-mixer",1],["푸드프로세서","food-processor",1],["식품건조기","food-dehydrator",1],["요구르트제조기","yogurt-maker",1],["빙수기","bingsu-machine",1],["아이스크림메이커","ice-cream-maker",1],["가정용정미기","rice-milling-machine",1],["전기레인지1구","single-burner-electric",1],["미니오븐","mini-oven",1],["전기약탕기","herb-medicine-pot",1],["중탕기","double-boiler-cooker",1],["탄산수제조기","soda-maker",1],["무선전기포트","cordless-kettle",1],["커피그라인더","coffee-grinder",1],["에스프레소머신","espresso-machine",1],["가정용맥주제조기","home-beer-maker",1],["전기훈제기","electric-smoker",1],["팝콘기","popcorn-maker",1],["미니밥솥","mini-rice-cooker",1],["보온고","food-warmer",1],["튀김기","deep-fryer",1],["전기석쇠","electric-roaster",1],["떡메이커","rice-cake-maker",1],["전기라면포트","ramen-cooker",1],["가정용커피로스터","coffee-roaster",1],["전기죽쑤개","porridge-cooker",1]],
  "생활가전":[["청소기","vacuum-cleaner",1],["무선청소기","cordless-vacuum",1],["로봇청소기","robot-vacuum",1],["스팀청소기","steam-cleaner",1],["물걸레청소기","mop-vacuum",1],["침구청소기","bed-vacuum",1],["핸디청소기","handy-vacuum",1],["정수기","water-purifier",1],["직수형정수기","direct-water-purifier",1],["언더싱크정수기","under-sink-purifier",1],["비데","bidet",1],["일체형비데","integrated-bidet",1],["재봉틀","sewing-machine",1],["오버로크재봉틀","overlock-sewing-machine",1],["다리미","iron",1],["스팀다리미","steam-iron",1],["스탠드스팀다리미","standing-steam-iron",1],["전기면도기","electric-shaver",1],["헤어드라이어","hair-dryer",1],["고데기","hair-styler",1],["전동칫솔","electric-toothbrush",1],["구강세정기","oral-irrigator",1],["체중계","body-scale",1],["체지방계","body-fat-scale",1],["혈압계","blood-pressure-monitor",1],["저주파마사지기","low-frequency-massager",1],["발마사지기","foot-massager",1],["종아리마사지기","leg-massager",1],["눈마사지기","eye-massager",1],["핸디마사지건","handheld-massage-gun",1],["의류압축기","clothes-compressor",1],["신발관리기","shoe-care-machine",1],["신발건조기","shoe-dryer",1],["살균건조기","uv-sterilizer-dryer",1],["젖병소독기","bottle-sterilizer",1],["손소독기","hand-sanitizer-dispenser",1],["전기모기채","electric-mosquito-swatter",2],["초음파세척기","ultrasonic-cleaner",1],["미니재봉틀","mini-sewing-machine",1],["가정용정수필터","water-filter-unit",1],["안마쿠션","massage-cushion",1],["가정용혈당계","glucose-meter",1],["전자체온계","digital-thermometer",1],["가습청정기","humidifying-purifier",1],["전기요","electric-blanket",1],["온열매트","heated-mattress-pad",1],["코털제거기","nose-hair-trimmer",1],["전동이발기","hair-clipper",1],["가정용혈압팔목계","wrist-blood-pressure-monitor",1],["휴대용가습기","portable-humidifier",1]],
  "계절가전":[["에어컨","air-conditioner",1,0.4],["벽걸이에어컨","wall-air-conditioner",1,0.2],["이동식에어컨","portable-air-conditioner",1,0.2],["창문형에어컨","window-air-conditioner",1,0.2],["선풍기","electric-fan",2,0.1],["스탠드선풍기","stand-fan",1,0.12],["타워팬","tower-fan",1,0.12],["써큘레이터","air-circulator",1,0.08],["벽걸이선풍기","wall-fan",1,0.08],["박스팬","box-fan",1,0.08],["제습기","dehumidifier",1,0.15],["가습기","humidifier",1,0.05],["초음파가습기","ultrasonic-humidifier",1,0.05],["가열식가습기","heated-humidifier",1,0.06],["공기청정기","air-purifier",1,0.12],["차량용공기청정기","car-air-purifier",1,0.02],["온풍기","fan-heater",1,0.08],["전기히터","electric-heater",1,0.1],["석유난로","kerosene-heater",1,0.12],["가스난로","gas-heater",1,0.12],["전기라디에이터","electric-radiator",1,0.12],["온수매트","hot-water-mat",1,0.04],["전기장판","electric-mat",1,0.04],["카본히터","carbon-heater",1,0.08],["할로겐히터","halogen-heater",1,0.08],["컨벡션히터","convection-heater",1,0.1],["난로가드","heater-guard",1,0.05],["온열기","radiant-heater",1,0.08],["원적외선히터","infrared-heater",1,0.09],["미니온풍기","mini-fan-heater",1,0.03],["충전식손난로","rechargeable-hand-warmer",2,0.005],["발난로","foot-warmer",1,0.03],["난방텐트","heating-tent",1,0.06],["제습제통","dehumidifier-box",4,0.01],["대형에어써큘","large-air-circulator",1,0.12],["산업용선풍기","industrial-fan",1,0.2],["대형제습기","large-dehumidifier",1,0.2],["에어커튼","air-curtain",1,0.1],["열풍기","hot-air-blower",1,0.1],["난방패널","heating-panel",1,0.08],["전기방석","heated-cushion",2,0.02],["화목난로","wood-stove",1,0.3],["펠릿난로","pellet-stove",1,0.3],["usb미니가습기","usb-mini-humidifier",1,0.005],["창문형환풍기","window-ventilator",1,0.05],["실링팬","ceiling-fan",1,0.1],["대형산업용히터","industrial-heater",1,0.25],["미니서큘레이터","mini-circulator",1,0.04],["가정용에어워셔","air-washer",1,0.1]],
  "영상·음향기기":[["TV","television",1],["대형TV","large-television",1],["벽걸이TV","wall-mount-tv",1],["프로젝터","projector",1],["빔프로젝터스크린","projector-screen",1],["사운드바","soundbar",1],["오디오스피커","audio-speaker",1],["북쉘프스피커","bookshelf-speaker",1],["우퍼","subwoofer",1],["블루투스스피커","bluetooth-speaker",1],["홈시어터","home-theater-system",1],["앰프","audio-amplifier",1],["리시버","av-receiver",1],["턴테이블","turntable",1],["CD플레이어","cd-player",1],["라디오","radio",1],["게임콘솔","game-console",1],["휴대용게임기","handheld-game-console",1],["VR헤드셋","vr-headset",1],["셋톱박스","set-top-box",1],["DVD플레이어","dvd-player",1],["블루레이플레이어","blu-ray-player",1],["카메라","camera",1],["DSLR카메라","dslr-camera",1],["캠코더","camcorder",1],["액션캠","action-camera",1],["삼각대","tripod",1],["조명스탠드촬영","studio-light",1],["마이크","microphone",1],["헤드폰","headphones",1],["헤드셋","gaming-headset",1],["이어폰케이스","earphone-case",1],["믹서콘솔","audio-mixer",1],["전자드럼","electronic-drum",1],["전자피아노","digital-piano",1],["신디사이저","synthesizer",1],["일렉기타앰프","guitar-amplifier",1],["노래방기기","karaoke-machine",1],["TV거치대이동식","tv-cart",1],["모니터스피커","monitor-speaker",1],["포터블프로젝터","portable-projector",1],["스마트빔","smart-beam",1],["레코드보관함","record-storage",1],["AV장식장","av-cabinet",1],["미니TV","mini-tv",1],["스마트TV32인치","smart-tv-32-inch",1],["빈티지라디오","vintage-radio",1],["보이스레코더","voice-recorder",1],["프로젝터천장마운트","projector-ceiling-mount",1],["사운드바우퍼세트","soundbar-woofer-set",1]],
  "컴퓨터·사무기기":[["데스크톱컴퓨터","desktop-computer",1],["모니터","monitor",1],["듀얼모니터","dual-monitor",1],["노트북","laptop",1],["올인원PC","all-in-one-pc",1],["미니PC","mini-pc",1],["키보드","keyboard",1],["마우스","mouse",1],["프린터","printer",1],["복합기","multifunction-printer",1],["레이저프린터","laser-printer",1],["스캐너","scanner",1],["문서세단기","paper-shredder",1],["코팅기","laminator",1],["복사기","copy-machine",1],["팩스기","fax-machine",1],["공유기","wifi-router",1],["NAS서버","nas-server",1],["외장하드","external-hard-drive",1],["UPS전원장치","ups-power-supply",1],["웹캠","webcam",1],["그래픽태블릿","graphic-tablet",1],["태블릿PC","tablet-pc",1],["모니터암","monitor-arm",1],["노트북거치대","laptop-stand",1],["USB허브","usb-hub",1],["멀티탭","power-strip",1],["프로젝션스캐너","document-scanner",1],["라벨프린터","label-printer",1],["영수증프린터","receipt-printer",1],["포스단말기","pos-terminal",1],["카드단말기","card-reader-terminal",1],["회의용스피커폰","conference-speakerphone",1],["화상회의카메라","video-conference-camera",1],["대형모니터34인치","monitor-34-inch",1],["게이밍PC","gaming-pc",1],["서버랙","server-rack",1],["산업용프린터","industrial-printer",1],["대형복합기","large-mfp",1],["제본기","binding-machine",1],["명함스캐너","business-card-scanner",1],["바코드스캐너","barcode-scanner",1],["출퇴근기록기","time-clock",1],["문서보관스캐너","archive-scanner",1],["미니빔프린터","photo-printer",1],["3D프린터","3d-printer",1],["플로터","plotter",1],["키오스크","kiosk",1],["모니터스탠드받침","monitor-riser",1],["노트북쿨러","laptop-cooler",1]],
  "거실가구":[["소파","sofa",1,0.6],["2인소파","two-seat-sofa",1,0.7],["3인소파","three-seat-sofa",1,0.9],["4인소파","four-seat-sofa",1,1.1],["코너소파","corner-sofa",1,1.3],["리클라이너","recliner",1,0.6],["소파베드","sofa-bed",1,1.0],["1인안락의자","armchair",1,0.4],["스툴","stool",2,0.1],["거실테이블","living-room-table",1,0.3],["소파테이블","sofa-side-table",1,0.15],["티테이블","coffee-table",1,0.25],["콘솔테이블","console-table",1,0.2],["TV장","tv-stand",1,0.4],["거실장","living-room-cabinet",1,0.5],["장식장","display-cabinet",1,0.5],["진열장","showcase-cabinet",1,0.5],["아트월수납장","art-wall-cabinet",1,0.5],["거실선반","living-room-shelf",1,0.2],["오디오장","audio-cabinet",1,0.3],["벽선반","wall-shelf",2,0.05],["파티션","room-partition",1,0.2],["빈백","bean-bag",1,0.3],["카펫","carpet",1,0.2],["러그","rug",1,0.1],["안마의자거실","living-massage-chair",1,0.8],["흔들의자","rocking-chair",1,0.4],["1인용리클라이너","single-recliner",1,0.6],["거실벤치","living-bench",1,0.3],["신문꽂이","magazine-rack",1,0.05],["화분받침대","plant-stand",2,0.05],["거실수납벤치","storage-bench",1,0.3],["소파쿠션세트","sofa-cushion-set",1,0.1],["거실커튼박스","curtain-box",1,0.1],["장스탠드조명","floor-lamp",1,0.1],["테이블조명","table-lamp",2,0.05],["벽걸이거울","wall-mirror",1,0.1],["전신거울","full-length-mirror",1,0.15],["거실책장낮은","low-bookshelf",1,0.3],["다용도선반","utility-shelf",1,0.2],["소파팔걸이트레이","sofa-arm-tray",1,0.02],["거실협탁","living-side-table",1,0.1],["거실장식선반","decorative-shelf",1,0.1],["엔틱콘솔","antique-console",1,0.3],["대형카펫","large-carpet",1,0.3],["코너장식장","corner-cabinet",1,0.4],["거실full수납장","living-storage-cabinet",1,0.6],["빈티지소파","vintage-sofa",1,0.9],["패브릭소파","fabric-sofa",1,0.9],["가죽소파","leather-sofa",1,1.0]],
  "침실가구":[["침대","bed",1,0.9],["싱글침대","single-bed",1,0.7],["슈퍼싱글침대","super-single-bed",1,0.8],["더블침대","double-bed",1,1.0],["퀸침대","queen-bed",1,1.1],["킹침대","king-bed",1,1.3],["매트리스","mattress",1,0.5],["토퍼","mattress-topper",1,0.15],["침대프레임","bed-frame",1,0.6],["헤드보드","headboard",1,0.2],["2층침대","bunk-bed",1,1.4],["패밀리침대","family-bed",1,1.5],["평상","floor-bed-platform",1,0.8],["돌침대","stone-bed",1,1.4],["흙침대","clay-bed",1,1.4],["장롱","wardrobe",1,1.2],["붙박이장문짝","builtin-closet-door",1,0.5],["옷장","clothes-closet",1,1.0],["행거옷장","hanger-closet",1,0.3],["드레스룸선반","dressroom-shelf",1,0.4],["화장대","dressing-table",1,0.4],["화장대의자","vanity-chair",1,0.1],["서랍장","chest-of-drawers",1,0.5],["3단서랍장","three-drawer-chest",1,0.4],["5단서랍장","five-drawer-chest",1,0.6],["협탁","nightstand",1,0.1],["침실협탁2","bedside-table",1,0.1],["이불장","bedding-cabinet",1,0.7],["경대","vanity-mirror-stand",1,0.3],["전신경대","standing-mirror-cabinet",1,0.3],["침실벤치","bedroom-bench",1,0.2],["침실화장경","bedroom-mirror",1,0.1],["옷걸이스탠드","coat-rack",1,0.1],["침대수납박스","under-bed-storage",2,0.1],["침실책장","bedroom-bookshelf",1,0.3],["주니어침대","junior-bed",1,0.5],["원목침대","wooden-bed",1,1.0],["철제침대","metal-bed-frame",1,0.7],["수납침대","storage-bed",1,1.1],["침대깔판","bed-slat-base",1,0.3],["대형장롱3문","three-door-wardrobe",1,1.3],["대형장롱4문","four-door-wardrobe",1,1.5],["슬라이딩장롱","sliding-wardrobe",1,1.3],["코너장롱","corner-wardrobe",1,1.0],["미닫이옷장","sliding-closet",1,1.2],["화장대세트","vanity-set",1,0.5],["침실full드레서","bedroom-dresser",1,0.6],["아기서랍장","baby-drawer-chest",1,0.4],["원목화장대","wooden-vanity",1,0.4],["침실전신거울장","mirror-wardrobe",1,1.0]],
  "주방가구":[["식탁","dining-table",1,0.5],["2인식탁","two-seat-dining-table",1,0.4],["4인식탁","four-seat-dining-table",1,0.6],["6인식탁","six-seat-dining-table",1,0.9],["식탁의자","dining-chair",4,0.1],["벤치의자","dining-bench",1,0.2],["아일랜드식탁","kitchen-island",1,0.7],["홈바테이블","home-bar-table",1,0.4],["바스툴","bar-stool",2,0.1],["주방수납장","kitchen-cabinet",1,0.6],["그릇장","dish-cabinet",1,0.6],["찬장","cupboard",1,0.6],["레인지대","range-stand",1,0.3],["전자레인지선반","microwave-shelf",1,0.2],["김치냉장고받침","fridge-base-stand",1,0.1],["주방아일랜드수납","island-storage",1,0.5],["食器정리선반","dish-rack-shelf",1,0.2],["주방틈새장","kitchen-slim-cabinet",1,0.2],["쌀통수납장","rice-storage-cabinet",1,0.2],["주방벤치수납","kitchen-storage-bench",1,0.3],["와인랙","wine-rack",1,0.15],["다용도주방선반","kitchen-utility-shelf",1,0.2],["주방트롤리","kitchen-trolley",1,0.2],["아일랜드바","island-bar",1,0.6],["원목식탁","wooden-dining-table",1,0.7],["대리석식탁","marble-dining-table",1,0.9],["접이식식탁","folding-dining-table",1,0.3],["확장형식탁","extendable-dining-table",1,0.8],["주방홈바장","home-bar-cabinet",1,0.5],["커피바테이블","coffee-bar-table",1,0.3],["주방후드장","hood-cabinet",1,0.2],["싱크대상부장","sink-upper-cabinet",1,0.4],["싱크대하부장","sink-lower-cabinet",1,0.5],["보조싱크대","auxiliary-sink-unit",1,0.5],["주방벽선반","kitchen-wall-shelf",2,0.05],["다이닝세트","dining-set",1,1.0],["주방틈새수납","kitchen-gap-storage",1,0.15],["양념선반","spice-shelf",1,0.05],["食기건조대장","dish-drying-cabinet",1,0.2],["주방코너장","kitchen-corner-cabinet",1,0.4],["원형식탁","round-dining-table",1,0.6],["4인다이닝세트","four-seat-dining-set",1,1.0],["6인다이닝세트","six-seat-dining-set",1,1.3],["접이식주방테이블","folding-kitchen-table",1,0.3],["주방보조테이블","kitchen-side-table",1,0.2],["빌트인식탁","builtin-dining-table",1,0.6],["주방스툴세트","kitchen-stool-set",1,0.2],["아침식탁","breakfast-table",1,0.4],["철제주방선반","metal-kitchen-shelf",1,0.2],["주방수납트레이장","tray-cabinet",1,0.2]],
  "아동가구":[["아기침대","infant-crib",1,0.5],["범퍼침대","bumper-bed",1,0.6],["유아침대","toddler-bed",1,0.5],["2층아동침대","kids-bunk-bed",1,1.2],["아동책상","kids-desk",1,0.3],["아동의자","kids-chair",2,0.1],["아동책상세트","kids-desk-set",1,0.4],["아동책장","kids-bookshelf",1,0.3],["장난감정리함","toy-storage-box",2,0.1],["장난감수납장","toy-cabinet",1,0.4],["아동옷장","kids-wardrobe",1,0.7],["아동서랍장","kids-drawer-chest",1,0.4],["기저귀교환대","diaper-changing-table",1,0.3],["수유쿠션","nursing-cushion",1,0.05],["아기바운서","baby-bouncer",1,0.1],["아기체어","baby-high-chair",1,0.15],["부스터의자","booster-seat",1,0.05],["유모차","stroller",1,0.3],["쌍둥이유모차","twin-stroller",1,0.4],["휴대용유모차","portable-stroller",1,0.15],["카시트","car-seat",1,0.2],["아기목욕통","baby-wash-tub",1,0.1],["아기침대모빌","crib-mobile",1,0.02],["놀이매트","play-mat",1,0.15],["아기울타리","baby-playpen",1,0.3],["볼풀장","ball-pit",1,0.2],["아동미끄럼틀","kids-slide",1,0.3],["실내그네","indoor-swing",1,0.15],["아동책꽂이","kids-book-rack",1,0.15],["아동소파","kids-sofa",1,0.2],["빈백아동","kids-bean-bag",1,0.15],["아동화장대","kids-vanity",1,0.2],["학습의자","study-chair-kids",1,0.15],["아동높이조절책상","height-adjustable-desk-kids",1,0.4],["아동행거","kids-hanger",1,0.1],["장난감텐트","toy-tent",1,0.1],["아기식탁의자","baby-dining-chair",1,0.15],["보행기","baby-walker",1,0.15],["아기침대가드","crib-guard",1,0.05],["아동2단책장","kids-two-tier-shelf",1,0.2],["원목아기침대","wooden-crib",1,0.5],["아동침대가드레일","bed-guard-rail",1,0.05],["아동수납벤치","kids-storage-bench",1,0.2],["아동전동차","kids-ride-on-car",1,0.3],["아기그네의자","baby-swing-chair",1,0.15],["아동책상수납","kids-desk-storage",1,0.2],["유아식탁","toddler-table",1,0.2],["아기침대매트리스","crib-mattress",1,0.1],["아동테이블세트","kids-table-set",1,0.3],["아동벽선반","kids-wall-shelf",2,0.03]],
  "사무가구":[["사무용책상","office-desk",1,0.5],["ㄱ자책상","l-shaped-desk",1,0.6],["회의용테이블","conference-table",1,1.0],["사무용의자","office-chair",1,0.3],["회의용의자","conference-chair",4,0.2],["임원의자","executive-chair",1,0.4],["파티션책상","partition-desk",1,0.6],["사무파티션","office-partition",1,0.2],["서류함","filing-cabinet",1,0.4],["3단서류함","three-tier-file-cabinet",1,0.4],["캐비닛","steel-cabinet",1,0.5],["철제캐비닛","metal-storage-cabinet",1,0.5],["사무용책장","office-bookshelf",1,0.4],["복사기받침대","copier-stand",1,0.2],["사물함","locker",1,0.5],["다인용사물함","multi-locker",1,0.9],["책상서랍유닛","desk-drawer-unit",1,0.15],["OA데스크","oa-desk",1,0.5],["스탠딩책상","standing-desk",1,0.5],["높이조절책상","height-adjustable-desk",1,0.5],["게이밍의자","gaming-chair",1,0.4],["메쉬의자","mesh-office-chair",1,0.3],["회의실화이트보드","conference-whiteboard",1,0.1],["이동식화이트보드","mobile-whiteboard",1,0.2],["게시판","bulletin-board",1,0.1],["안내데스크","reception-desk",1,0.8],["카운터","service-counter",1,0.7],["사무용소파","office-sofa",1,0.6],["응접세트","reception-sofa-set",1,1.2],["도서관책장","library-bookshelf",1,0.6],["복합기수납장","printer-cabinet",1,0.3],["문서보관함대형","large-document-cabinet",1,0.7],["금고","safe-box",1,0.2],["대형금고","large-safe",1,0.5],["우편함","mailbox-unit",1,0.2],["사무선반","office-shelf",1,0.3],["철제앵글선반","angle-steel-shelf",1,0.4],["서고이동식","mobile-shelving",1,0.9],["프로젝터스탠드","projector-stand",1,0.2],["회의용원형테이블","round-conference-table",1,0.8],["1인부스","office-booth",1,0.8],["사무용발받침","office-footrest",1,0.05],["모니터받침선반","monitor-shelf-office",1,0.1],["사무용트롤리","office-trolley",1,0.2],["작업대","workbench",1,0.6],["실험실책상","lab-desk",1,0.6],["교탁","lectern",1,0.3],["강의용책상","lecture-desk",1,0.5],["학생용책걸상","student-desk-chair",1,0.4],["대형회의테이블12인","conference-table-12",1,1.4]],
  "수납가구":[["수납장","storage-cabinet",1,0.4],["다용도수납장","multipurpose-cabinet",1,0.4],["플라스틱서랍장","plastic-drawer",1,0.3],["리빙박스","living-box",3,0.08],["압축팩정리함","vacuum-storage-bag",4,0.02],["행거","clothes-hanger-rack",1,0.2],["드레스행거","dress-hanger-stand",1,0.25],["스탠드행거","standing-hanger",1,0.2],["신발장","shoe-cabinet",1,0.4],["대형신발장","large-shoe-cabinet",1,0.6],["회전신발장","rotating-shoe-rack",1,0.3],["우산꽂이","umbrella-stand",1,0.05],["책장","bookshelf",1,0.4],["5단책장","five-tier-bookshelf",1,0.5],["철제선반","metal-rack",1,0.4],["앵글선반","angle-shelf",1,0.4],["틈새수납장","slim-storage-cabinet",1,0.2],["코너선반","corner-shelf",1,0.1],["벽수납장","wall-storage-cabinet",1,0.3],["다단서랍정리함","multi-drawer-organizer",2,0.1],["의류수납함","clothes-storage-box",3,0.08],["이불정리함","bedding-storage-box",2,0.1],["장난감수납선반","toy-storage-shelf",1,0.3],["현관수납장","entryway-cabinet",1,0.5],["팬트리장","pantry-cabinet",1,0.5],["다용도철제선반","utility-metal-shelf",1,0.4],["바퀴달린수납함","rolling-storage-cart",1,0.15],["서랍정리트레이","drawer-tray",4,0.01],["옷정리선반","closet-organizer",1,0.2],["모자수납선반","hat-rack",1,0.05],["가방수납장","bag-storage-cabinet",1,0.3],["공구수납장","tool-storage-cabinet",1,0.4],["약품수납장","medicine-cabinet",1,0.15],["화장품수납장","cosmetic-organizer",1,0.1],["주류수납장","liquor-cabinet",1,0.3],["신문잡지선반","magazine-shelf",1,0.1],["다목적정리함대형","large-storage-bin",2,0.15],["침대밑수납","under-bed-drawer",2,0.1],["벽걸이선반세트","wall-shelf-set",1,0.1],["코너수납타워","corner-storage-tower",1,0.3],["회전수납타워","rotating-storage-tower",1,0.2],["철제3단카트","three-tier-metal-cart",1,0.15],["대나무선반","bamboo-shelf",1,0.2],["원목수납장","wooden-storage-cabinet",1,0.5],["플라스틱정리함대","large-plastic-bin",3,0.1],["미니서랍정리함","mini-drawer-organizer",2,0.03],["문서수납박스","document-storage-box",3,0.05],["의류압축정리함","compression-storage-box",3,0.05],["빌트인수납장","builtin-storage",1,0.6],["다용도틈새선반","gap-utility-shelf",1,0.15]],
  "욕실용품":[["전기수건건조대","towel-warmer",1],["세면대수납장","bathroom-vanity-cabinet",1],["욕실선반","bathroom-shelf",1],["욕실코너선반","bathroom-corner-shelf",1],["수건걸이","towel-rack",1],["수건보관함","towel-storage",1],["욕실거울장","bathroom-mirror-cabinet",1],["욕실의자","bath-stool",2],["욕조","bathtub",1,0.4],["아기욕조","baby-bath-tub",1],["샤워부스","shower-booth",1,0.3],["샤워커튼봉","shower-curtain-rod",1],["변기커버세트","toilet-cover-set",1],["휴지걸이","toilet-paper-holder",1],["욕실매트","bath-mat",2],["빨래바구니","laundry-basket",1],["빨래건조대욕실","bathroom-drying-rack",1],["욕실수납카트","bathroom-cart",1],["칫솔살균기","toothbrush-sterilizer",1],["비누디스펜서","soap-dispenser",1],["샴푸디스펜서","shampoo-dispenser",1],["욕실슬리퍼정리","slipper-rack",1],["세탁세제수납함","detergent-storage",1],["욕실환풍기","bathroom-fan",1],["샤워헤드세트","shower-head-set",1],["욕실전신거울","bathroom-full-mirror",1],["좌욕기","sitz-bath",1],["족욕기","foot-bath",1],["욕실히터","bathroom-heater",1],["방수매트","waterproof-mat",1],["욕조받침대","bathtub-caddy",1],["샤워타월걸이","shower-towel-bar",1],["세면볼","wash-basin",1],["욕실수납선반3단","bathroom-3tier-shelf",1],["변기솔세트","toilet-brush-set",1],["욕실코너수납","bath-corner-storage",1],["세탁바구니이동식","rolling-laundry-basket",1],["욕실미끄럼방지매트","anti-slip-bath-mat",2],["욕실등","bathroom-light",1],["샤워기헤드","shower-head",1],["욕실화분선반","bath-plant-shelf",1]],
  "주방용품":[["냄비세트","pot-set",1],["프라이팬세트","frying-pan-set",1],["압력솥","pressure-cooker",1],["찜솥","steamer-pot",1],["전골냄비","hot-pot",1],["그릇세트","dish-set",1],["접시세트","plate-set",1],["밥그릇국그릇세트","bowl-set",1],["유리컵세트","glass-cup-set",1],["머그컵세트","mug-set",1],["수저세트","cutlery-set",1],["칼도마세트","knife-cutting-board-set",1],["믹싱볼세트","mixing-bowl-set",1],["밀폐용기세트","food-container-set",1],["반찬통세트","side-dish-container-set",1],["도시락통","lunch-box",2],["보온병","thermos",2],["텀블러","tumbler",2],["주전자","kettle-stovetop",1],["찻잔세트","tea-cup-set",1],["와인잔세트","wine-glass-set",1],["식기건조대","dish-drying-rack",1],["수저통","utensil-holder",1],["양념통세트","spice-container-set",1],["쌀통","rice-container",1],["김치통대형","large-kimchi-container",2],["물병세트","water-bottle-set",1],["채반세트","colander-set",1],["대야","basin",2],["소쿠리","strainer-basket",2],["플라스틱바구니","plastic-basket",3],["조리도구세트","cooking-utensil-set",1],["국자뒤집개세트","ladle-turner-set",1],["강판","grater",1],["절구","mortar-pestle",1],["도마세트","cutting-board-set",1],["쟁반세트","tray-set",1],["냄비받침세트","pot-holder-set",1],["행주앞치마세트","apron-set",1],["커피드리퍼세트","coffee-dripper-set",1],["보온도시락","insulated-lunch-box",1],["김치냉장고통세트","kimchi-container-set",1],["대형솥","large-cauldron",1],["떡판","rice-cake-board",1],["제빵도구세트","baking-tool-set",1],["와인오프너세트","wine-opener-set",1],["주방저울","kitchen-scale",1],["아이스박스주방","kitchen-ice-box",1],["보냉가방","cooler-bag",1],["실리콘조리세트","silicone-utensil-set",1]],
  "생활용품":[["커튼","curtain",1],["암막커튼","blackout-curtain",1],["블라인드","blinds",1],["롤스크린","roll-screen",1],["복도러그","hallway-rug",1],["러그매트","rug-mat",1],["거실장식액자","picture-frame",3],["대형액자","large-frame",1],["벽시계","wall-clock",1],["탁상시계","desk-clock",1],["스탠드조명","floor-lamp-living",1],["무드등","mood-light",2],["전신거울생활","standing-mirror",1],["화분","flower-pot",3],["대형화분","large-planter",1],["조화장식","artificial-plant",2],["빨래건조대","laundry-drying-rack",1],["대형빨래건조대","large-drying-rack",1],["다리미판","ironing-board",1],["옷걸이세트","hanger-set",1],["빨래바구니생활","laundry-hamper",1],["재봉정리함","sewing-box",1],["우산","umbrella",2],["장우산꽂이","umbrella-holder",1],["방석세트","floor-cushion-set",1],["쿠션","cushion",4],["담요","blanket",3],["이불세트","comforter-set",2],["베개세트","pillow-set",2],["매트리스커버","mattress-cover",2],["돗자리","picnic-mat",1],["방문발","door-curtain",1],["현관매트","entrance-mat",2],["신발정리대","shoe-organizer",1],["벽걸이수납포켓","wall-pocket-organizer",1],["옷정리압축봉","clothing-rod",1],["빨래집게통","clothespin-box",1],["재활용분리함","recycle-bin-set",1],["쓰레기통","trash-can",2],["대형쓰레기통","large-trash-bin",1],["방향제디퓨저","diffuser",2],["가습기생활","room-humidifier",1],["실내온습도계","hygrometer",1],["문틈방풍재","door-draft-stopper",2],["미니선풍기생활","mini-desk-fan",2],["탁상용정리함","desk-organizer",2],["약통정리함","pill-organizer",1],["세탁망세트","laundry-net-set",1],["여행용파우치","travel-pouch-set",1],["다용도바구니","utility-basket",3]],
  "청소용품":[["청소도구세트","cleaning-tool-set",1],["빗자루쓰레받기","broom-dustpan-set",1],["대걸레","mop",1],["회전밀대걸레","spin-mop",1],["스팀걸레","steam-mop-pad",1],["유리창청소기","window-squeegee",1],["먼지떨이","duster",2],["청소솔세트","cleaning-brush-set",1],["양동이","cleaning-bucket",2],["물청소밀대","floor-squeegee",1],["세제수납카트","cleaning-cart",1],["진공청소포집기","dust-collector",1],["압축분무기","pressure-sprayer",1],["분무기세트","spray-bottle-set",1],["고무장갑세트","rubber-glove-set",1],["청소포행주","cleaning-cloth-set",1],["극세사걸레","microfiber-mop",2],["변기청소솔","toilet-brush",1],["배수구청소도구","drain-cleaning-tool",1],["에어컨청소분사기","ac-cleaning-spray",1],["카펫청소솔","carpet-brush",1],["차량청소도구세트","car-cleaning-set",1],["고압세척기","pressure-washer",1],["물걸레교체패드","mop-refill-pad",4],["청소기필터","vacuum-filter",2],["롤클리너","lint-roller",3],["먼지제거테이프","dust-tape",2],["빗자루장대","long-handle-broom",1],["창틀청소솔","window-track-brush",1],["다용도세척솔","utility-scrub-brush",2],["청소용사다리","cleaning-step-stool",1],["쓰레기봉투홀더","trash-bag-holder",1],["재활용집게","recycle-tongs",1],["바닥왁스도포기","wax-applicator",1],["카펫세척기","carpet-cleaner",1],["진드기제거기","dust-mite-cleaner",1],["환풍기청소솔","fan-cleaning-brush",1],["청소용앞치마","cleaning-apron",1],["대형청소밀대","large-floor-mop",1],["업소용대걸레","commercial-mop",1],["청소용양동이카트","mop-bucket-cart",1],["미세먼지청소기","fine-dust-vacuum",1],["가정용소독분무기","disinfectant-sprayer",1],["청소용호스","cleaning-hose",1],["바닥광택기","floor-polisher",1],["청소용발판사다리","cleaning-ladder",1],["빗자루세트대형","large-broom-set",1],["먼지흡입브러시","dust-brush-attachment",2],["곰팡이제거솔","mold-removal-brush",1],["다용도청소통","cleaning-caddy",1]],
  "운동·레저용품":[["러닝머신","treadmill",1,0.6],["실내자전거","exercise-bike",1,0.4],["일립티컬","elliptical-machine",1,0.6],["로잉머신","rowing-machine",1,0.4],["벤치프레스","bench-press",1,0.4],["덤벨세트","dumbbell-set",1,0.15],["바벨세트","barbell-set",1,0.2],["케틀벨","kettlebell",2,0.05],["요가매트","yoga-mat",1],["폼롤러","foam-roller",1],["짐볼","gym-ball",1],["철봉","pull-up-bar",1],["푸쉬업바","push-up-bar",1],["스텝퍼","stepper",1],["훌라후프","hula-hoop",1],["줄넘기","jump-rope",2],["복싱샌드백","punching-bag",1],["인바디체중계","body-composition-scale",1],["안마롤러","massage-roller",1],["헬스벤치","weight-bench",1,0.3],["파워랙","power-rack",1,0.5],["골프가방","golf-bag",1,0.2],["골프채세트","golf-club-set",1,0.2],["골프연습매트","golf-practice-mat",1],["스크린골프기기","screen-golf-set",1,0.3],["탁구대","table-tennis-table",1,0.8],["당구대","billiard-table",1,1.2],["다트판","dart-board",1],["농구골대","basketball-hoop",1,0.4],["배드민턴세트","badminton-set",1],["테니스라켓세트","tennis-racket-set",1],["야구배트글러브","baseball-set",1],["축구공세트","soccer-ball-set",2],["스키용품세트","ski-equipment-set",1,0.3],["스노보드","snowboard",1,0.2],["보드가방","board-bag",1,0.2],["인라인스케이트","inline-skates",1],["킥보드","kick-scooter",1,0.2],["전동킥보드","electric-scooter",1,0.25],["자전거","bicycle",1,0.4],["로드자전거","road-bike",1,0.4],["MTB자전거","mountain-bike",1,0.4],["전기자전거","electric-bicycle",1,0.45],["세발자전거","tricycle",1,0.2],["헬멧보호대세트","helmet-pad-set",1],["서핑보드","surfboard",1,0.2],["카약","kayak",1,0.5],["패들보드","paddle-board",1,0.3],["등산배낭","hiking-backpack",1],["운동기구정리랙","fitness-storage-rack",1,0.3]],
  "캠핑용품":[["텐트","tent",1,0.2],["대형텐트","large-tent",1,0.3],["원터치텐트","pop-up-tent",1,0.15],["타프","tarp",1,0.1],["캠핑의자","camping-chair",2,0.1],["캠핑테이블","camping-table",1,0.15],["폴딩박스","folding-box",2,0.08],["아이스박스","cooler-box",1,0.15],["캠핑침대","camping-cot",1,0.15],["에어매트","air-mattress",1,0.1],["침낭","sleeping-bag",2,0.08],["캠핑랜턴","camping-lantern",2],["헤드랜턴","head-lamp",2],["버너","camping-stove",1],["가스토치","gas-torch",1],["화로대","fire-pit-stand",1,0.1],["그릴망세트","grill-net-set",1],["캠핑코펠","camping-cookware",1],["캠핑식기세트","camping-dish-set",1],["캠핑주전자","camping-kettle",1],["캠핑칼도마","camping-knife-board",1],["캠핑수납장","camping-storage-cabinet",1,0.2],["캠핑카트","camping-wagon",1,0.2],["캠핑선반","camping-shelf",1,0.1],["캠핑행어","camping-hanger",1],["폴딩웨건","folding-wagon",1,0.2],["캠핑매트","camping-mat",2,0.08],["롤테이블","roll-table",1,0.1],["캠핑난로","camping-heater",1,0.1],["캠핑팬히터","camping-fan-heater",1],["캠핑선풍기","camping-fan",1],["캠핑전등스탠드","camping-light-stand",1],["타프폴대","tarp-pole",1],["팩망치세트","peg-hammer-set",1],["캠핑파라솔","camping-parasol",1,0.1],["해먹","hammock",1],["캠핑그늘막","camping-shade",1,0.1],["캠핑발전기","camping-generator",1,0.15],["파워뱅크대용량","portable-power-station",1],["캠핑샤워기","portable-camping-shower",1],["캠핑정수기","camping-water-filter",1],["캠핑화장실텐트","camping-toilet-tent",1,0.1],["캠핑조리대","camping-kitchen-stand",1,0.15],["캠핑용쿨러가방","camping-cooler-bag",1],["캠핑연료통","fuel-canister",2],["캠핑도끼톱세트","camping-axe-saw-set",1],["캠핑테이블세트","camping-table-set",1,0.2],["차박매트","car-camping-mat",1,0.1],["루프탑텐트","rooftop-tent",1,0.4],["캠핑수납가방","camping-duffel-bag",2,0.1]],
  "반려동물용품":[["강아지집","dog-house",1],["고양이집","cat-house",1],["애견하우스대형","large-pet-house",1,0.2],["캣타워","cat-tower",1,0.3],["대형캣타워","large-cat-tower",1,0.4],["애견울타리","pet-fence",1,0.2],["반려동물켄넬","pet-kennel",1,0.15],["이동장","pet-carrier",1],["대형이동장","large-pet-carrier",1,0.15],["반려동물유모차","pet-stroller",1,0.2],["강아지방석","pet-cushion",2],["펫침대","pet-bed",1],["대형펫쿠션","large-pet-cushion",1],["사료통","pet-food-container",1],["자동급식기","automatic-feeder",1],["자동급수기","automatic-water-dispenser",1],["급식대","pet-feeding-stand",1],["고양이화장실","cat-litter-box",1],["자동고양이화장실","automatic-litter-box",1],["강아지배변판","dog-potty-tray",1],["펫계단","pet-stairs",1],["펫카시트","pet-car-seat",1],["반려동물목욕조","pet-bathtub",1],["펫드라이룸","pet-dry-room",1,0.2],["펫드라이어","pet-dryer",1],["강아지옷수납함","pet-clothes-box",1],["장난감바구니펫","pet-toy-basket",1],["스크래처","cat-scratcher",2],["햄스터케이지","hamster-cage",1],["새장","bird-cage",1],["대형새장","large-bird-cage",1,0.2],["어항","fish-tank",1,0.15],["대형어항","large-aquarium",1,0.3],["수조받침대","aquarium-stand",1,0.2],["파충류사육장","reptile-terrarium",1,0.15],["강아지방석대형","large-dog-bed",1],["펫매트","pet-mat",2],["반려동물휀스대형","large-pet-playpen",1,0.2],["펫간식보관함","pet-treat-jar",1],["강아지리드줄정리","leash-holder",1],["펫샤워기","pet-shower-head",1],["고양이터널","cat-tunnel",1],["펫런닝휠","pet-running-wheel",1],["강아지운동장매트","pet-play-mat",1],["펫정수기","pet-water-fountain",1],["펫체중계","pet-scale",1],["반려동물이동가방","pet-sling-bag",1],["강아지계단수납","pet-step-storage",1],["펫하우스텐트","pet-tent",1],["캣폴","cat-pole",1,0.2]],
  "기타 이삿짐 및 폐기물":[["이삿짐박스","moving-box",10,0.08],["대형이삿짐박스","large-moving-box",5,0.12],["의류박스","wardrobe-box",3,0.15],["압축비닐봉투","vacuum-plastic-bag",5,0.02],["비닐봉투대형","large-plastic-bag",10,0.01],["뽁뽁이완충재","bubble-wrap-roll",2,0.05],["이사용테이프","packing-tape",5],["폐가전","waste-appliance",1,0.4],["폐가구","waste-furniture",1,0.5],["폐냉장고","waste-refrigerator",1,0.9],["폐TV","waste-tv",1,0.2],["폐매트리스","waste-mattress",1,0.5],["폐소파","waste-sofa",1,0.9],["폐침대","waste-bed",1,0.9],["폐책상","waste-desk",1,0.4],["대형폐기물","bulky-waste",1,0.4],["폐목재","waste-wood",1,0.2],["철거잔재","demolition-debris",1,0.3],["재활용품묶음","recycling-bundle",3,0.1],["헌옷수거","old-clothes-bag",3,0.1],["폐지묶음","waste-paper-bundle",3,0.08],["고철","scrap-metal",1,0.15],["폐가전에어컨","waste-air-conditioner",1,0.3],["폐세탁기","waste-washing-machine",1,0.6],["폐건조기","waste-dryer",1,0.6],["폐장롱","waste-wardrobe",1,1.0],["화분폐기","waste-flower-pot",2,0.05],["폐피아노","waste-piano",1,1.0],["폐운동기구","waste-fitness-equipment",1,0.4],["정원용품","garden-tools",1,0.1],["잔디깎이","lawn-mower",1,0.2],["사다리","ladder",1,0.15],["접이식사다리","folding-ladder",1,0.15],["공구함","toolbox",1,0.1],["대형공구함","large-toolbox",1,0.2],["작업공구세트","tool-set",1,0.1],["전동드릴세트","power-drill-set",1],["페인트도구세트","paint-tool-set",1],["화분식물대형","large-potted-plant",1,0.15],["장독대항아리","earthenware-jar",2,0.1],["김장독","kimjang-jar",2,0.15],["대형화분정원","garden-planter",1,0.15],["자전거거치대","bike-rack",1,0.15],["창고선반","warehouse-shelf",1,0.4],["폐타이어","waste-tire",2,0.1],["이사폐기물자루","waste-sack",5,0.05],["대형거울폐기","waste-mirror",1,0.1],["폐카펫","waste-carpet",1,0.15],["폐자전거","waste-bicycle",1,0.4],["기타잡화박스","misc-box",5,0.08]],
};

// 필수 대표 품목의 '정확한 표기'를 보장하기 위해 추가합니다.
const MUST = {
  "대형가전": [["김치스텐드냉장고","kimchi-stand-refrigerator",1,0.7],["세라잼","ceragem",1,0.7]],
  "주방가전": [["오븐","oven",1]],
  "침실가구": [["모션침대","motion-bed-frame",1,1.0]],
  "사무가구": [["책상","desk",1,0.5],["의자","chair",4,0.2]],
  "청소용품": [["청소도구","cleaning-tools",1]],
  "운동·레저용품": [["스키용품","ski-gear",1,0.2]],
  "생활용품": [["여행가방","suitcase",2,0.1],["액자","photo-frame",3]],
  "기타 이삿짐 및 폐기물": [["폐기물","general-waste",1,0.3]],
};
for (const [cat, list] of Object.entries(MUST)) {
  DATA[cat] = (DATA[cat] || []).concat(list);
}

const slugOk = (s) => /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(s);
const items = [];
const seenName = new Map();
const seenFile = new Map();
const problems = [];
for (const [cat, list] of Object.entries(DATA)) {
  const meta = CATS[cat];
  if (!meta) { problems.push(`알 수 없는 카테고리: ${cat}`); continue; }
  const baseCount = {};
  for (const row of list) {
    const [name, slug, qty, vol] = row;
    if (!slugOk(slug)) { problems.push(`파일명 규칙 위반: ${slug} (${name})`); continue; }
    baseCount[slug] = (baseCount[slug] || 0) + 1;
    const file = `${slug}-${String(baseCount[slug]).padStart(2, "0")}`;
    const id = file;
    if (seenName.has(name)) problems.push(`중복 한글명: ${name} (${cat} ↔ ${seenName.get(name)})`);
    else seenName.set(name, cat);
    if (seenFile.has(file)) problems.push(`중복 파일명: ${file}`);
    else seenFile.set(file, cat);
    items.push({ id, name, file, cat20: cat, folder: meta.folder, qty: qty ?? 1, vol: vol ?? meta.vol, emoji: meta.emoji, path: `/assets/items-3d/${meta.folder}/${file}.webp` });
  }
}
const perCat = {};
for (const it of items) perCat[it.cat20] = (perCat[it.cat20] || 0) + 1;
console.log("== 카테고리별 개수 ==");
for (const c of Object.keys(CATS)) console.log(`  ${c}: ${perCat[c] || 0}`);
console.log(`== 총 품목: ${items.length}`);
console.log(`== 중복/오류: ${problems.length}`);
for (const p of problems) console.log("   ! " + p);

if (problems.length === 0 && process.argv.includes("--emit")) {
  // 1) 데이터 TS
  const cats20 = Object.keys(CATS);
  const ts = `// 이 파일은 스크립트로 생성됩니다. 직접 수정하지 마세요. (scratchpad/gen-items.mjs)
// 짐픽 품목 마스터 — 견적서·고객정보·직원공유가 공통으로 사용하는 단일 소스.
export interface Item1000 {
  id: string;
  /** 한글 품목명 */
  name: string;
  /** 영문 파일명(소문자+하이픈) */
  file: string;
  /** 20개 카테고리 */
  cat20: string;
  /** 아이콘 경로 폴더 */
  folder: string;
  /** 기본 수량 */
  qty: number;
  /** 예상 부피(m³) */
  vol: number;
  /** 폴백 이모지 */
  emoji: string;
  /** 3D webp 아이콘 경로(없으면 <Icon3D>가 기본 박스로 대체) */
  path: string;
}

export const CATS20: string[] = ${JSON.stringify(cats20, null, 0)};

export const ITEMS_1000: Item1000[] = ${JSON.stringify(items, null, 0)};
`;
  const tsPath = `${REPO}/src/lib/items-catalog-1000.ts`;
  mkdirSync(dirname(tsPath), { recursive: true });
  writeFileSync(tsPath, ts);
  // 2) 프롬프트 CSV
  const esc = (s) => `"${String(s).replace(/"/g, '""')}"`;
  const style = "bright clean premium 3D icon, isometric, soft studio lighting, subtle soft drop shadow, transparent background, glossy rounded style, centered, 1:1, no text no logo no watermark";
  let csv = "file,name_ko,cat20,prompt\n";
  for (const it of items) {
    const base = it.file.replace(/-\d+$/, "").replace(/-/g, " ");
    csv += [esc(it.file), esc(it.name), esc(it.cat20), esc(`A ${style}, of a ${base}`)].join(",") + "\n";
  }
  const csvPath = `${REPO}/docs/icon-image-prompts.csv`;
  mkdirSync(dirname(csvPath), { recursive: true });
  writeFileSync(csvPath, csv);
  console.log(`\n생성됨:\n  ${tsPath}\n  ${csvPath}`);
}
