/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareIdRouteImport } from './routes/share.$id'
import { Route as BillingCallbackRouteImport } from './routes/billing.callback'
import { Route as StaffEstimateTokenRouteImport } from './routes/staff.estimate.$token'
import { Route as ApiPublicItemIconFileRouteImport } from './routes/api/public/item-icon.$file'
import { Route as ApiPublicHooksSendMoveRemindersRouteImport } from './routes/api/public/hooks/send-move-reminders'
import { Route as ApiPublicHooksFixNoticeRouteImport } from './routes/api/public/hooks/fix-notice'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareIdRoute = ShareIdRouteImport.update({
  id: '/share/$id',
  path: '/share/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingCallbackRoute = BillingCallbackRouteImport.update({
  id: '/billing/callback',
  path: '/billing/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffEstimateTokenRoute = StaffEstimateTokenRouteImport.update({
  id: '/staff/estimate/$token',
  path: '/staff/estimate/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicItemIconFileRoute = ApiPublicItemIconFileRouteImport.update({
  id: '/api/public/item-icon/$file',
  path: '/api/public/item-icon/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSendMoveRemindersRoute =
  ApiPublicHooksSendMoveRemindersRouteImport.update({
    id: '/api/public/hooks/send-move-reminders',
    path: '/api/public/hooks/send-move-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksFixNoticeRoute = ApiPublicHooksFixNoticeRouteImport.update({
  id: '/api/public/hooks/fix-notice',
  path: '/api/public/hooks/fix-notice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/billing/callback': typeof BillingCallbackRoute
  '/share/$id': typeof ShareIdRoute
  '/staff/estimate/$token': typeof StaffEstimateTokenRoute
  '/api/public/hooks/fix-notice': typeof ApiPublicHooksFixNoticeRoute
  '/api/public/hooks/send-move-reminders': typeof ApiPublicHooksSendMoveRemindersRoute
  '/api/public/item-icon/$file': typeof ApiPublicItemIconFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/billing/callback': typeof BillingCallbackRoute
  '/share/$id': typeof ShareIdRoute
  '/staff/estimate/$token': typeof StaffEstimateTokenRoute
  '/api/public/hooks/fix-notice': typeof ApiPublicHooksFixNoticeRoute
  '/api/public/hooks/send-move-reminders': typeof ApiPublicHooksSendMoveRemindersRoute
  '/api/public/item-icon/$file': typeof ApiPublicItemIconFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/billing/callback': typeof BillingCallbackRoute
  '/share/$id': typeof ShareIdRoute
  '/staff/estimate/$token': typeof StaffEstimateTokenRoute
  '/api/public/hooks/fix-notice': typeof ApiPublicHooksFixNoticeRoute
  '/api/public/hooks/send-move-reminders': typeof ApiPublicHooksSendMoveRemindersRoute
  '/api/public/item-icon/$file': typeof ApiPublicItemIconFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/billing/callback'
    | '/share/$id'
    | '/staff/estimate/$token'
    | '/api/public/hooks/fix-notice'
    | '/api/public/hooks/send-move-reminders'
    | '/api/public/item-icon/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/billing/callback'
    | '/share/$id'
    | '/staff/estimate/$token'
    | '/api/public/hooks/fix-notice'
    | '/api/public/hooks/send-move-reminders'
    | '/api/public/item-icon/$file'
  id:
    | '__root__'
    | '/'
    | '/reset-password'
    | '/billing/callback'
    | '/share/$id'
    | '/staff/estimate/$token'
    | '/api/public/hooks/fix-notice'
    | '/api/public/hooks/send-move-reminders'
    | '/api/public/item-icon/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  BillingCallbackRoute: typeof BillingCallbackRoute
  ShareIdRoute: typeof ShareIdRoute
  StaffEstimateTokenRoute: typeof StaffEstimateTokenRoute
  ApiPublicHooksFixNoticeRoute: typeof ApiPublicHooksFixNoticeRoute
  ApiPublicHooksSendMoveRemindersRoute: typeof ApiPublicHooksSendMoveRemindersRoute
  ApiPublicItemIconFileRoute: typeof ApiPublicItemIconFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$id': {
      id: '/share/$id'
      path: '/share/$id'
      fullPath: '/share/$id'
      preLoaderRoute: typeof ShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/callback': {
      id: '/billing/callback'
      path: '/billing/callback'
      fullPath: '/billing/callback'
      preLoaderRoute: typeof BillingCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/estimate/$token': {
      id: '/staff/estimate/$token'
      path: '/staff/estimate/$token'
      fullPath: '/staff/estimate/$token'
      preLoaderRoute: typeof StaffEstimateTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/item-icon/$file': {
      id: '/api/public/item-icon/$file'
      path: '/api/public/item-icon/$file'
      fullPath: '/api/public/item-icon/$file'
      preLoaderRoute: typeof ApiPublicItemIconFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-move-reminders': {
      id: '/api/public/hooks/send-move-reminders'
      path: '/api/public/hooks/send-move-reminders'
      fullPath: '/api/public/hooks/send-move-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendMoveRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/fix-notice': {
      id: '/api/public/hooks/fix-notice'
      path: '/api/public/hooks/fix-notice'
      fullPath: '/api/public/hooks/fix-notice'
      preLoaderRoute: typeof ApiPublicHooksFixNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  BillingCallbackRoute: BillingCallbackRoute,
  ShareIdRoute: ShareIdRoute,
  StaffEstimateTokenRoute: StaffEstimateTokenRoute,
  ApiPublicHooksFixNoticeRoute: ApiPublicHooksFixNoticeRoute,
  ApiPublicHooksSendMoveRemindersRoute: ApiPublicHooksSendMoveRemindersRoute,
  ApiPublicItemIconFileRoute: ApiPublicItemIconFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
