/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareIdRouteImport } from './routes/share.$id'
import { Route as ManageIdRouteImport } from './routes/manage.$id'
import { Route as StaffEstimateTokenRouteImport } from './routes/staff.estimate.$token'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareIdRoute = ShareIdRouteImport.update({
  id: '/share/$id',
  path: '/share/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageIdRoute = ManageIdRouteImport.update({
  id: '/manage/$id',
  path: '/manage/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffEstimateTokenRoute = StaffEstimateTokenRouteImport.update({
  id: '/staff/estimate/$token',
  path: '/staff/estimate/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/share/$id': typeof ShareIdRoute
  '/manage/$id': typeof ManageIdRoute
  '/staff/estimate/$token': typeof StaffEstimateTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/share/$id': typeof ShareIdRoute
  '/manage/$id': typeof ManageIdRoute
  '/staff/estimate/$token': typeof StaffEstimateTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/share/$id': typeof ShareIdRoute
  '/manage/$id': typeof ManageIdRoute
  '/staff/estimate/$token': typeof StaffEstimateTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/share/$id'
    | '/manage/$id'
    | '/staff/estimate/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reset-password' | '/share/$id' | '/manage/$id' | '/staff/estimate/$token'
  id:
    | '__root__'
    | '/'
    | '/reset-password'
    | '/share/$id'
    | '/manage/$id'
    | '/staff/estimate/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShareIdRoute: typeof ShareIdRoute
  ManageIdRoute: typeof ManageIdRoute
  StaffEstimateTokenRoute: typeof StaffEstimateTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$id': {
      id: '/share/$id'
      path: '/share/$id'
      fullPath: '/share/$id'
      preLoaderRoute: typeof ShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/$id': {
      id: '/manage/$id'
      path: '/manage/$id'
      fullPath: '/manage/$id'
      preLoaderRoute: typeof ManageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/estimate/$token': {
      id: '/staff/estimate/$token'
      path: '/staff/estimate/$token'
      fullPath: '/staff/estimate/$token'
      preLoaderRoute: typeof StaffEstimateTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShareIdRoute: ShareIdRoute,
  ManageIdRoute: ManageIdRoute,
  StaffEstimateTokenRoute: StaffEstimateTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
